export enum AuthActionTypes {
	API_RESPONSE_SUCCESS = '@@auth/API_RESPONSE_SUCCESS',
	API_RESPONSE_ERROR = '@@auth/API_RESPONSE_ERROR',

	LOGIN_USER = '@@auth/LOGIN_USER',
	LOGOUT_USER = '@@auth/LOGOUT_USER',
	SIGNUP_USER = '@@auth/SIGNUP_USER',
	VERIFY_CODE = '@@auth/VERIFY_CODE',
	SEND_VERIFICATION = '@@auth/SEND_VERIFICATION',
	FORGOT_PASSWORD = '@@auth/FORGOT_PASSWORD',
	FORGOT_PASSWORD_CHANGE = '@@auth/FORGOT_PASSWORD_CHANGE',
	PASSWORD_VERIFY_CODE = '@@auth/PASSWORD_VERIFY_CODE',

	RESET = '@@auth/RESET'
}
